spring:
    profiles:
      active: dev
    application:
      name: microservice-config-client8080
server:
  port: 4001

---
spring:
  profiles: dev

---
spring:
  profiles: test

---

spring:
  profiles: prod # 生产环境