spring:
    profiles:
      active: dev
    application:
      name: microservice-config-client8080
---


spring:
  profiles: dev

---

server:
  port: 4001
spring:
  profiles: test

---

server:
  port: 4001 #端口号
spring:
  profiles: prod # 生产环境